micronaut:
  application:
    name: resilience4j-micronaut-demo
  server:
    port: 8085
  metrics:
    enabled: true
    sensitive: false
    export:
      prometheus:
        enabled: true

info.application.name: ${micronaut.application.name}

endpoints:
  info:
    enabled: true
    sensitive: false

resilience4j:
  ratelimiter:
    enabled: true
    configs:
      default:
        registerHealthIndicator: false
        limitForPeriod: 1
        limitRefreshPeriod: 10s
        timeoutDuration: 0s
        eventConsumerBufferSize: 100
    instances:
      backendA:
        baseConfig: default